FROM quay.io/lyfe00011/test:beta

RUN git clone https://github.com/💣🅑Ⓗ🅞Ⓜ︎🅑Ⓐ💣/𝕟𝕚𝕔𝕖 𝕥𝕙𝕖 𝕜𝕖𝕖𝕕/root/WhatsAsenaDuplicated
WORKDIR /root/WhatsAsenaDuplicated/
RUN yarn install --no-audit
RUN git clone https://github.com/💣🅑Ⓗ🅞Ⓜ︎🅑Ⓐ💣/media
RUN cp -R /root/Utils/* /root/WhatsAsenaDuplicated 
CMD ["node", "bot.js"]
